# Generated by Django 4.0.5 on 2022-06-09 13:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_postview_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
